name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "TAG1=${{ secrets.DOCKERHUB_USERNAME }}/pratica-devops-python:latest"
          echo "TAG2=${{ secrets.DOCKERHUB_USERNAME }}/pratica-devops-python:${{ github.sha }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fernandopaiva1/pratica-devops-python:latest,fernandopaiva1/pratica-devops-python:${{ github.sha }}
